apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_USER: admin
  MYSQL_PASSWORD: "1234"
  MYSQL_DATABASE: demo

  # DB_URL: jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  # DB_HOST: "mysql-service"
  DB_USERNAME: admin
  DB_PASSWORD: "1234"